import os
from groq import Groq

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))


def report_writer(
    company: str,
    overview: str,
    news: str,
    financials: str,
    risks: str
) -> str:
    """Compile all agent outputs into a structured research report"""
    print(f"✍️ Report Writer compiling report for {company}...")

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0.2,
        messages=[
            {
                "role": "system",
                "content": """You are a senior financial analyst writing a research report.
Structure the report with these exact sections:

## Company Overview
[2-3 sentences describing what the company does]

## Recent News & Developments
[3-4 bullet points from recent news]

## Financial Performance
[Key metrics and what they mean — use the actual numbers]

## Key Risk Factors
[Top 3 risks with brief explanation]

## Investment Thesis
[2-3 sentences summarizing the overall picture]

⚠️ Disclaimer: This report is generated by AI for informational 
purposes only and does not constitute financial advice. Always 
consult a qualified financial advisor before making investment decisions.

Be concise, factual, and professional."""
            },
            {
                "role": "user",
                "content": f"""Compile a research report for {company}:

COMPANY OVERVIEW (from SEC filing):
{overview}

RECENT NEWS:
{news}

FINANCIAL METRICS:
{financials}

RISK FACTORS:
{risks}"""
            }
        ]
    )

    result = response.choices[0].message.content
    print("✅ Report Writer done!")
    return result